<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Administrator',
                'email' => 'admin@admin.com',
                'username' => 'admin',
                'role_id' => -1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$RWHJUBM2AKMmbUyR5T136OTzqRZrNbyxt5z5VWicq70sbkY61a/aG',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-06 01:38:15',
                'updated_at' => '2021-01-06 01:38:15',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Maricar U. Ortiz',
                'email' => 'liphcaraga@gmail.com',
                'username' => 'Maricar Ortiz',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$d9FI6vufGjz/l507LO6UiuQnUbd1hhDjWuLwCuWxeTVVD5kX/UtXW',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 11:18:47',
                'updated_at' => '2021-01-11 11:18:47',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Ernesto Pareja',
                'email' => 'lhschiefdohro13@gmail.com',
                'username' => 'ERNESTO PAREJA',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$UmF2asVgfSsLQy.i.s10hupXzGnBr4ruryi7yQzVYsjNv4Zr8aKea',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 11:50:34',
                'updated_at' => '2021-01-11 11:50:34',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'NANCY S. JELIANGGAO',
                'email' => 'trainingsec.doh13@gmail.com',
                'username' => 'NSJ.hrdu',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3Z9MmxeLtvq58CCEgwKsi.C6qrWjHEzWkmrAGnm/0D4LtkNPyyhA2',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 11:50:47',
                'updated_at' => '2021-01-11 11:50:47',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'HERODINA T. PRESTON',
                'email' => 'dohcaraga_governance@yahoo.com.ph',
                'username' => 'htpreston',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$X/qbFiYiZ.AbFYPm5pFf5.VVOoco7ac3wi.iZnRCJBpVtpcXlMOC.',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 12:02:25',
                'updated_at' => '2021-01-11 12:02:25',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Glee D. Valenzona',
                'email' => 'dohro13ho@gmail.com',
                'username' => 'hfdu caraga',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$ulH6FWffz07BhjCWSFQtJOBwsLKc2dcbECP49rFl0dqBpkzZzDXLq',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 12:40:27',
                'updated_at' => '2021-02-13 13:14:34',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Ma. Dorothy C. Hornido',
                'email' => 'dohro13map@gmail.com',
                'username' => 'dohmaip',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$dgVkQP3U1OhcO0Rqf2F90OaprohZj7.M1uLN23947Acxc9CY/Q5Mq',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 12:50:34',
                'updated_at' => '2021-01-11 12:50:34',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Gina B. Urbiztondo',
                'email' => 'ginbis1225@gmail.com',
                'username' => 'gbu',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$6E/cXivuV.quYWNYUNVdMOeMQOj7UWBpQ2xwBJgyWwFMisHkEim3q',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 13:16:21',
                'updated_at' => '2021-01-11 13:16:21',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'EMMI MARIE J. CABAHUG',
                'email' => 'gad.doh13@gmail.com',
                'username' => 'EMMI',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$1SnazwIIQWtrx.g4eg5yYO8GQfHfYpG4TpSn7tVSVxpk3smXwIcSC',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 13:19:20',
                'updated_at' => '2021-01-11 13:19:20',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'DIOSCORO NAVARRO JR',
                'email' => 'navz07@yahoo.com',
                'username' => 'dmn',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$QwqaDvovikUuynfMK4iIveAsYTtXcPwT908JgTfjFc5ekGACaYt6e',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 14:35:24',
                'updated_at' => '2021-01-11 14:35:24',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'AGNES L. CULLANTES',
                'email' => 'noncomm.lhs@gmail.com',
                'username' => 'alc',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$RX51cMI8WT4tNJfeXuQKDONRo5SaQqyBqyh7RnVatGbvAppMZmEAm',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 14:35:39',
                'updated_at' => '2021-01-11 14:35:39',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'SUNSHINE A. ALIPAYO',
                'email' => 'nvbsp.caraga@gmail.com',
                'username' => 'saa',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$uaTsSkLjy2fQyQBmuRw.T.KiAJaKb/Uqiod.c6vt416E/ky.ringm',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 14:43:59',
                'updated_at' => '2021-01-11 14:43:59',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'ROWENA O. PABIA',
                'email' => 'nmhp.caraga@gmail.com',
                'username' => 'rop',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$LwwglpjNe3LsGbD1uF3lpeaIOZ7amlfQJpRc13Bph//3ooytSiX3S',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 14:46:23',
                'updated_at' => '2021-01-11 14:46:23',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'Romelyn Esther C. Torralba',
                'email' => 'dohroxiiihpu@gmail.com',
                'username' => 'RECTORRALBA',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3LXs2gBXfblFvrJF6QxgA.VKfooH.DWgAkyA4ZVsEIRKreU8K1rbC',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-11 15:40:29',
                'updated_at' => '2021-01-11 15:40:29',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'GLADYS D. BULADACO',
                'email' => 'ict.dohro13@gmail.com',
                'username' => 'GDBULADACO',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$JM11nyf3Tm3mVXCQxyyAh.hB6ZgVYH28onSDNkd9EZ9Whj4SdxANm',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-12 08:27:42',
                'updated_at' => '2021-02-11 13:25:32',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'faith opada',
                'email' => 'farahluna70@yahoo.com',
                'username' => 'faith opada',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$XMJ0..u.i3.UWrDfVIm0XeHtSm62Z.0yu8mFLP7AEHm2O9ouAfvsa',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-12 13:16:06',
                'updated_at' => '2021-01-12 13:16:06',
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'Maria Carmela My A. Beltran',
                'email' => 'vincent.hfep@gmail.com',
                'username' => 'HFEP',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$KdQBtyvbh.8kkGtc8rDqv.Hzrz5L6QsYViUtMm1q7TcpTCfMsUtoO',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-12 14:38:45',
                'updated_at' => '2021-01-12 14:38:45',
            ),
            17 => 
            array (
                'id' => 20,
                'name' => 'Faith P. Opada',
                'email' => 'ntddoh13@gmail.com',
                'username' => 'fpopada',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$KjmIn57HCMZSyIGKzSb1n.qqgDEr4mX/N2sz.dX9WpOrywgN47/Ou',
                'status' => 'INACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-12 15:01:42',
                'updated_at' => '2021-01-25 16:08:55',
            ),
            18 => 
            array (
                'id' => 21,
                'name' => 'JEAN AGANAP PINGAL',
                'email' => 'doh_procurement@yahoo.com',
                'username' => 'KYLEXY94',
                'role_id' => 4,
                'email_verified_at' => NULL,
                'password' => '$2y$10$2pexAd2/8QJwKMIlEHbcHeIWxHv8nZh3rwlvjATqNSdeH8S4z7cUi',
                'status' => 'INACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 09:24:18',
                'updated_at' => '2021-02-11 09:17:38',
            ),
            19 => 
            array (
                'id' => 22,
                'name' => 'Jenalyn Reveche',
                'email' => 'dohro13cashier@gmail.com',
                'username' => 'cashier',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$yMrQFC/7CCwXOYiE7DRM7eprVuNa1rdJhM2bM09kVfHKkqwnWECm.',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 10:59:44',
                'updated_at' => '2021-01-13 10:59:44',
            ),
            20 => 
            array (
                'id' => 23,
                'name' => 'JEAN PINGAL',
                'email' => 'kylejohneguna@gmail.com',
                'username' => 'KYLEGWAPO94',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Xe9c4i0Fd3Dcl1ICzzxPkOv.hJG9yJm7VluN/lmhsbUTUkv/voaPG',
                'status' => 'INACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:30:23',
                'updated_at' => '2021-02-10 13:02:46',
            ),
            21 => 
            array (
                'id' => 24,
                'name' => 'Leslie C. Cortes',
                'email' => 'lesliecimagalacortes@gmail.com',
                'username' => 'lccortes',
                'role_id' => 5,
                'email_verified_at' => NULL,
                'password' => '$2y$10$KyefvtIMA9KNfeZY0O3s4exa/VK5kqnWjW/1NppyIbb6AprT0znoy',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:34:55',
                'updated_at' => '2021-01-13 15:34:55',
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'JEAN AGANAP PINGAL',
                'email' => 'kj@gmail.com',
                'username' => 'Kylegwapo',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$vOVqfyJV2xMMJAaW7mErZecf9rZPD8ulZb/Ifk9PcSESyV2cW4T0.',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:38:09',
                'updated_at' => '2021-02-10 12:58:19',
            ),
            23 => 
            array (
                'id' => 26,
                'name' => 'Leslie C. Cortes',
                'email' => 'edpms.dohro13@gmail.com',
                'username' => 'lccortes2',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$gQAMng5RXDIATCiMBH6oTupN4a3tIMZmslH4i2drrVou0TOE05De2',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:40:46',
                'updated_at' => '2021-01-13 15:40:46',
            ),
            24 => 
            array (
                'id' => 27,
                'name' => 'Arlene D. Santua',
                'email' => 'arlene_santua76@yahoo.com.ph',
                'username' => 'Arlene Santua',
                'role_id' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$ypK75rDbpZ0dreEdANU/t.OO7CfMV.yqqQT4Eo8B9ul6x1JZdITmy',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:43:21',
                'updated_at' => '2021-01-13 15:43:21',
            ),
            25 => 
            array (
                'id' => 28,
                'name' => 'Arlene D. Santua',
                'email' => 'planningchdcaraga@gmail.com',
                'username' => 'A.Santua',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$vTSyXVuoJVsMcg2DpV7vu.rqNqNsXvGhfzLFYCkfhF.EpKjwTts46',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:47:50',
                'updated_at' => '2021-01-13 15:47:50',
            ),
            26 => 
            array (
                'id' => 29,
                'name' => 'Sharon Coja',
                'email' => 'sharoncoja386@gmail.com',
                'username' => 'shawi',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$rV.f/0FBaxfDWXZ1iZQtZuA3/Km4q23mpQhwDeCFYeQTm0hXb5ygu',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:52:54',
                'updated_at' => '2021-01-13 15:52:54',
            ),
            27 => 
            array (
                'id' => 30,
                'name' => 'Dinnes Karl N. Garcia',
                'email' => 'researchdohcaraga@gmail.com',
                'username' => 'HSRMT',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$oUwzHg3Cqb7m5QCw050/rO.y/Et617ISmBb2Co4CgmSIhAjS3TmHS',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:53:38',
                'updated_at' => '2021-01-13 15:53:38',
            ),
            28 => 
            array (
                'id' => 31,
                'name' => 'Cheryl Mary L. Plaza',
                'email' => 'cmlplaza@yahoo.com',
                'username' => 'cmlplaza',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$OWLp.dBwmoDeJKX1IfwP7OYSKjv/pMleO3kDAV0G3XsNTZf7/WLNG',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 15:59:27',
                'updated_at' => '2021-01-13 15:59:27',
            ),
            29 => 
            array (
                'id' => 32,
                'name' => 'DR. GARCE MARTINEZ-LIM',
                'email' => 'mnchn.chdcaraga@gmail.com',
                'username' => 'grace123',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$kAYKxI5wM/6mqitB5a/vn.rPtx7JClC.dh8XtLX9JXVlGO97vhnXu',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 16:05:59',
                'updated_at' => '2021-01-13 16:05:59',
            ),
            30 => 
            array (
                'id' => 33,
                'name' => 'Maria Linda Mercado',
                'email' => 'lindalmercado@gmail.com',
                'username' => 'ORAL',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$3ctGsMBm3DZ5NhCG3EvWme894enFlvs0I3lsY4v8.cZJAbGrQaXDe',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 16:07:09',
                'updated_at' => '2021-01-13 16:07:09',
            ),
            31 => 
            array (
                'id' => 34,
                'name' => 'TERESITA LINA P. MEDRANO',
                'email' => 'nutritiondoh@gmail.com',
                'username' => 'lina123',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$XUGAT0UC5KN0zuccBSVG5.rTGKzzY7eyadVmj70Kuv9DKPs81mFXi',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 16:08:38',
                'updated_at' => '2021-02-09 12:52:04',
            ),
            32 => 
            array (
                'id' => 35,
                'name' => 'Dinnes Karl N. Garcia',
                'email' => 'd.garcia11790@gmail.com',
                'username' => 'AHDP',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$ok36Sj1Zx3qOBwYC6hWCLuwea1bFWW1iiatxqnJXx1GAZ9F49ZPWa',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 16:10:14',
                'updated_at' => '2021-01-13 16:10:14',
            ),
            33 => 
            array (
                'id' => 36,
                'name' => 'JOCELYN P. MAGDULA',
                'email' => 'ellenjoymagduk@gmail.com',
                'username' => 'jocelyn',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$11eF/d6bcEp6W8jby3tkmOtj6pmF42cI2s8M5FJpkVdTbazdXfFim',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-13 16:13:52',
                'updated_at' => '2021-01-13 16:13:52',
            ),
            34 => 
            array (
                'id' => 37,
                'name' => 'Jean Aganap-Pingal',
                'email' => 'dohro13budget@gmail.com',
                'username' => 'admin_budget',
                'role_id' => 2,
                'email_verified_at' => NULL,
                'password' => '$2y$10$KTQPIzsBe3ANYomPEO0MXeuX7xoabpLJMdL34ao3KrdbDTg4Ng6Im',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-14 13:55:06',
                'updated_at' => '2021-01-29 13:52:36',
            ),
            35 => 
            array (
                'id' => 38,
                'name' => 'Erna T. Cravajal',
                'email' => 'ernz_m56@yahoo.com.ph',
                'username' => 'erna',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$lWHQ9loSK2h9Tto95Q17luaLXLuN4GRq/txf66X7ZqxppOBndLyGO',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-14 14:25:47',
                'updated_at' => '2021-01-14 14:25:47',
            ),
            36 => 
            array (
                'id' => 39,
                'name' => 'HELEN A CAÑO',
                'email' => 'dohphtsds@yahoo.com.ph',
                'username' => 'DOHPHTSDS',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$XqVZEWFdj9x77jre6YWdKeRrJGI2go8U.d678MnEhmbrFD1ZsXLYq',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-14 14:38:38',
                'updated_at' => '2021-01-14 14:38:38',
            ),
            37 => 
            array (
                'id' => 40,
                'name' => 'DRY RUN',
                'email' => 'dryrun@gmail.com',
                'username' => 'dryrun',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Uedj39xngB16c.F5TAauo.EId/nLKfjSahpqajqgRRZE61PaOU5JW',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-15 13:38:38',
                'updated_at' => '2021-01-15 13:38:38',
            ),
            38 => 
            array (
                'id' => 41,
                'name' => 'end user',
                'email' => 'enduser@gmail.com',
                'username' => 'enduser',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$M8ht2.y2ZTtwAeu1BwiZy.GMd/Mq47gHY3sw0Y0g57d5xCmEpFUma',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-19 14:57:51',
                'updated_at' => '2021-01-19 14:57:51',
            ),
            39 => 
            array (
                'id' => 42,
                'name' => 'JONATHAN RUBI BASADRE',
                'email' => 'denguecontrolprogram@gmail.com',
                'username' => 'jrbasadre',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$mpvvfUjG/M6t2RttfpQiIesC8y2D2xaoEafkdUH9B2gWSP9SJcvEy',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-01-20 09:24:07',
                'updated_at' => '2021-01-20 09:24:07',
            ),
            40 => 
            array (
                'id' => 43,
                'name' => 'ENGR. ARLENE D. SANTUA',
                'email' => 'arlene_santua76@yahoo.com',
                'username' => 'admin_planning',
                'role_id' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$XvE8hMpcGb/KNaqY0s1HoeQF3cK5q1jvlQVTRVzR9apbifBn/iG8i',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-03 09:47:02',
                'updated_at' => '2021-02-03 09:47:02',
            ),
            41 => 
            array (
                'id' => 44,
                'name' => 'Agnes Cullantes',
                'email' => 'daptp.caraga@gmail.com',
                'username' => 'NCDCullantes',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$8OsRX8avlc41/ZRitw22wOMd96uFr61Zucr2B4vu/2HNpbBQC.DSe',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 10:46:00',
                'updated_at' => '2021-02-09 10:46:00',
            ),
            42 => 
            array (
                'id' => 45,
                'name' => 'user',
                'email' => 'user@gmail.com',
                'username' => 'user',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4a13W.Qlbj7LesJ8lB1DMOKf.YtJlms5PiuLa2UpoVB86fiiz7pZm',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 10:46:56',
                'updated_at' => '2021-02-09 10:46:56',
            ),
            43 => 
            array (
                'id' => 46,
                'name' => 'Niel H. Nituda',
                'email' => 'nielnitz69@yahoo.com',
                'username' => 'nielnitz69',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$B1XBDo5a2e4U6NJZcYhBL.kpjAlWSLtZJTHaHt1GBznyVMXpbO1t2',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 11:09:06',
                'updated_at' => '2021-02-09 11:09:06',
            ),
            44 => 
            array (
                'id' => 47,
                'name' => 'Arlene Serrano',
                'email' => 'molina2rlyn@yahoo.com',
                'username' => 'aserrano',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DlMm8cdXrBNHYLinwLUYD.SXQVrCfYYKJWSbk2N36bVeSyaCdVIGy',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 11:12:53',
                'updated_at' => '2021-02-09 11:12:53',
            ),
            45 => 
            array (
                'id' => 48,
                'name' => 'Maria Ferma K. Liwat',
                'email' => 'caraga.rled@gmail.com',
                'username' => 'kliwat',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$yyZy5Vxh1S/F76zUdUewne6LESpglaAWlQurWKd1.lWIj883nbhAm',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 11:46:22',
                'updated_at' => '2021-02-09 11:46:22',
            ),
            46 => 
            array (
                'id' => 49,
                'name' => 'Erna T. Cravajal',
                'email' => 'ecravajal56@gmail.com',
                'username' => 'etcmalaria',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$H/NTLbzxCDEJjxX8EfVd.u/X76iC0jLj7XpYYbB.OmDqkQEYlmH/u',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 13:08:32',
                'updated_at' => '2021-02-09 13:08:32',
            ),
            47 => 
            array (
                'id' => 50,
                'name' => 'Maricar test',
                'email' => 'Maricartest@gmail.com',
                'username' => 'Maricartest',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$La0aet19c3jATYCSElwTBersjccm1mYBMo.s.EM/dhWIjv9.M/IEK',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 14:46:39',
                'updated_at' => '2021-02-09 14:46:39',
            ),
            48 => 
            array (
                'id' => 51,
                'name' => 'Mara Test',
                'email' => 'maravanessaa@gmail.com',
                'username' => 'Maratest',
                'role_id' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$x1EHOGdHRmiyFoIEZsEXsuPGhsam3WzMMpiuSc3KxTCsOBlrgoM2W',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 14:49:46',
                'updated_at' => '2021-02-09 14:49:46',
            ),
            49 => 
            array (
                'id' => 52,
                'name' => 'Aivan Test',
                'email' => 'acmmp_89@yahoo.com',
                'username' => 'aivan test',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$T97pK0TFLmPy0qofPHjoQeyxY9SvjsoNI7CfYCxRZDCQSiLU/oN7a',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 14:50:03',
                'updated_at' => '2021-02-09 14:50:03',
            ),
            50 => 
            array (
                'id' => 53,
                'name' => 'Mara Test 2',
                'email' => 'maravanessaa123@gmail.com',
                'username' => 'Mara Test 2',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$zqGsmfEWrzaIN959SDxJJeL5TX7dhdn9PEG.AAbXTxIeUb3.LbmlC',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-09 15:12:38',
                'updated_at' => '2021-02-09 15:12:38',
            ),
            51 => 
            array (
                'id' => 54,
                'name' => 'DR. GERNA MANATAD',
                'email' => 'sdn.dohcaraga@gmail.com',
                'username' => 'gernmanatad',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$TtwlX3A/a.QT/cS1LckD3OG4ZBXwAidB3lMhKEnOAj9VPj1JXhsIi',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-10 09:16:49',
                'updated_at' => '2021-02-10 09:16:49',
            ),
            52 => 
            array (
                'id' => 55,
                'name' => 'butuancdoho',
                'email' => 'butuancdoho@gmail.com',
                'username' => 'CDOHO',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$yARduY9hxuLlygVy992.cOnZ34ax8LSj6xGyNH/J3ueqRNpnSIxW.',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-10 10:01:43',
                'updated_at' => '2021-02-10 10:01:43',
            ),
            53 => 
            array (
                'id' => 56,
                'name' => 'JONATHAN RUBI BASADRE',
                'email' => 'ereid.caraga@gmail.com',
                'username' => 'EREID.CARAGA',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$tEfAFklolrpp2h/T0en4bu2gISdiIyVyzm3HRCUrg5C9D2DT7PlWi',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-10 10:41:30',
                'updated_at' => '2021-02-10 10:41:30',
            ),
            54 => 
            array (
                'id' => 57,
                'name' => 'JOMELA C. TORRES',
                'email' => 'jomelatorres@yahoo.com',
                'username' => 'jct',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$mmPhfFeX6osMt0oI8FIP7.QNHl.0ge/EYmeJoPDgjbT3W.OBsmery',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-10 11:32:42',
                'updated_at' => '2021-02-10 11:32:42',
            ),
            55 => 
            array (
                'id' => 59,
                'name' => 'Jean Aganap-Pingal',
                'email' => 'zhean66@gmail.com',
                'username' => 'zhean',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$OCkrPufLklkyabByMaX5b.1tueJ6wgzJp/HYgQ8DsKSSum2Vrq3oW',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-10 12:46:17',
                'updated_at' => '2021-02-10 13:15:42',
            ),
            56 => 
            array (
                'id' => 60,
                'name' => 'Romelyn Esther Torralba',
                'email' => 'dohcaragahpu@gmail.com',
                'username' => 'romelyn',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$zAVxVTLGwxsx/ZJ.nyTI7eS0f/N45/d5Ip275vGe.nl22a.okOKNC',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 09:20:15',
                'updated_at' => '2021-02-11 09:20:15',
            ),
            57 => 
            array (
                'id' => 61,
                'name' => 'Eleanor Lakag',
                'email' => 'supplydohcaraga@gmail.com',
                'username' => 'lakag',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$t0a7mwUIHEZxOGQfNGP49exmUoMBzNt1hlMeC/oH0E/djV8qHec7.',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:05:16',
                'updated_at' => '2021-02-11 13:05:16',
            ),
            58 => 
            array (
                'id' => 62,
                'name' => 'Sionny R. Apas',
                'email' => 'dohard@gmail.com',
                'username' => 'Sionny',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$yMHs0G8IWmg1arQRj/TeTOiZeZCOW.Twp1NEvSif4gU9xH51RQ.ba',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:19:03',
                'updated_at' => '2021-02-11 13:19:03',
            ),
            59 => 
            array (
                'id' => 63,
                'name' => 'Jay Ryan F. Villasurda',
                'email' => 'jayryanvillasurda@gmail.com',
                'username' => 'jayryan',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$dMU5Tjx3o3bgQUU5R5afBe2n6XCbEbQl5FB5LwCdJ3ky76LHm.lHK',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:19:22',
                'updated_at' => '2021-02-11 13:19:22',
            ),
            60 => 
            array (
                'id' => 64,
                'name' => 'Nancy Sarabosing Jelianggao',
                'email' => 'drc.chd13doh@gmail.com',
                'username' => 'Nancy_ISO',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$szZBU13EuJC9Il1IKIqFge345tfDXjN3W10rjQvQD5vtUJPaqnKB6',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:23:32',
                'updated_at' => '2021-02-11 13:23:32',
            ),
            61 => 
            array (
                'id' => 65,
                'name' => 'Ian Chester Tibe',
                'email' => 'ianchester91@gmail.com',
                'username' => 'ianchester',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$EpPZREBOjVkqq2g5KGCbo.Bl5FXbi8QUsNrkeneO56iM6uhsnmlNy',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:23:55',
                'updated_at' => '2021-02-11 13:23:55',
            ),
            62 => 
            array (
                'id' => 66,
                'name' => 'MA ANTOINETTA A FERNANDEZ',
                'email' => 'dohro13caraga@gmail.com',
                'username' => 'tonet.fernandez',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$8BxyseE2qIuuUPguXOFLa.lM/nFZc4gVCwDSP03HceouMBB9sfhF6',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:25:14',
                'updated_at' => '2021-02-11 13:25:14',
            ),
            63 => 
            array (
                'id' => 67,
                'name' => 'John Paul Ortiz',
                'email' => 'john@gmail.com',
                'username' => 'jp',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$dsxI1G8cfS01OmUoZOmp..RZCmq8YjCaQtYcqm068iQrHxO73Kcy6',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:28:38',
                'updated_at' => '2021-02-11 13:28:38',
            ),
            64 => 
            array (
                'id' => 68,
                'name' => 'Shogel T. Tinampay',
                'email' => 'shogeltinampay@gmail.com',
                'username' => 'Legosh',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$BXkT0QF5XqjlMOJn7UHxC.suErVoXRZp8plz4UjTwTPXUqtgIBKJq',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:29:21',
                'updated_at' => '2021-02-11 13:29:21',
            ),
            65 => 
            array (
                'id' => 69,
                'name' => 'Lemar Magadan Arnego',
                'email' => 'lemar.m.arnego@gmail.com',
                'username' => 'arnegolemar',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$CNZ8roYUJilP2roHhFOQ/eLr9YSSNpDPBghuhAcwJMTcjbP3VcdGO',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:30:33',
                'updated_at' => '2021-02-11 13:30:33',
            ),
            66 => 
            array (
                'id' => 70,
                'name' => 'Antonio C. Medroso',
                'email' => 'chd13dpo@gmail.com',
                'username' => 'acm2021',
                'role_id' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$10$vpRSVHqbCAo5v3t2.0jOluOtPR0uFH9bsUtguEMoXmfcvlbeQEYjK',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:37:17',
                'updated_at' => '2021-02-11 13:37:17',
            ),
            67 => 
            array (
                'id' => 71,
                'name' => 'Antonio C. Medroso',
                'email' => 'acmedroso2015@gmail.com',
                'username' => 'acmedroso2021',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$Z4mpyRzpVwIMvuOegCAM5.itJFQkxtWwtyG0N.hecoDjdS/LMGY6m',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 13:39:10',
                'updated_at' => '2021-02-11 13:39:10',
            ),
            68 => 
            array (
                'id' => 72,
                'name' => 'Glynna B. Andoy',
                'email' => 'pdohosds@gmail.com',
                'username' => 'glynna2021',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$5AoroU71p6GMNgaiU5/nh.sZdi8B50rFKaT6SWDJwHU.7P5M.Ah/y',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 14:31:29',
                'updated_at' => '2021-02-11 14:31:29',
            ),
            69 => 
            array (
                'id' => 73,
                'name' => 'JANE LUGO',
                'email' => 'pdohadn@gmail.com',
                'username' => 'janelugo',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$HTlfJ5higJySFUkDtEB2O.Rz4Hml4gA80kdAUgRBDh/O5vD3zgvTS',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 14:43:31',
                'updated_at' => '2021-02-11 14:43:31',
            ),
            70 => 
            array (
                'id' => 74,
                'name' => 'Sandria C. Yu',
                'email' => 'pdoho.ads@gmail.com',
                'username' => 'pdoho.ads',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$56tQnm23amLTV91b8xzSweDvB0M4BUB2gKtAqQgsq6yPkQ6u4Qmx2',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-02-11 14:45:21',
                'updated_at' => '2021-02-11 14:45:21',
            ),
            71 => 
            array (
                'id' => 75,
                'name' => 'demo',
                'email' => 'demo@gmail.com',
                'username' => 'demo',
                'role_id' => 3,
                'email_verified_at' => NULL,
                'password' => '$2y$10$iPIeaRBKf0iSK7FclfQ.QOl317ajO8eMbtibv7N3T60SBLcnRg.a2',
                'status' => 'ACTIVE',
                'remember_token' => NULL,
                'created_at' => '2021-03-01 17:52:38',
                'updated_at' => '2021-03-01 17:52:38',
            ),
        ));
        
        
    }
}